plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'java'
}

group = mod_group_id
version = "${minecraft_version}-fabric-${mod_version}"

base {
    archivesName = mod_id
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    runs {
        client {
            client()
            setConfigName('StructureNoOverlap Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('StructureNoOverlap Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }

    mixin.setDefaultRefmapName("${mod_id}.refmap.json")
}

processResources {
    def replaceProperties = [
            minecraft_version: minecraft_version,
            loader_version: loader_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: project.version,
            fabric_api_version: fabric_api_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]

    inputs.properties replaceProperties
    filteringCharset = 'UTF-8'

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}
