plugins {
    id 'fabric-loom' version "${loom_version}"
}

group = mod_group_id
version = "${minecraft_version}-fabric-${mod_version}"

base {
    archivesName = mod_id
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings "net.fabricmc:yarn:${yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
}

loom {
    mixin.setDefaultRefmapName("${mod_id}.refmap.json")
}

processResources {
    inputs.properties([
            minecraft_version: minecraft_version,
            fabric_loader_version: fabric_loader_version,
            fabric_api_version: fabric_api_version,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: project.version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ])

    filteringCharset = 'UTF-8'
    filesMatching('fabric.mod.json') {
        expand([
                minecraft_version: minecraft_version,
                fabric_loader_version: fabric_loader_version,
                fabric_api_version: fabric_api_version,
                mod_id: mod_id,
                mod_name: mod_name,
                mod_license: mod_license,
                mod_version: project.version,
                mod_authors: mod_authors,
                mod_description: mod_description
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
